from dotenv import load_dotenv
load_dotenv()
import os
import asyncio
from asyncio import TaskGroup
import re
from langchain_community.vectorstores import Chroma
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_core.documents import Document
from langchain_core.exceptions import OutputParserException
from typing import List, Annotated
from typing_extensions import TypedDict
from enum import Enum
from utils.evaluators import (documents_evaluator_chain,
                                hallucinations_evaluator_chain,
                                completeness_evaluator_chain,
                                rag_pipeline,
                                retry_rag_pipeline,
                                )

# Set the key TOKENIZERS_PARALLELISM to avoid deadlocks
os.environ["TOKENIZERS_PARALLELISM"] = "false"

# Defining embeddings generator
embeddings = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")

# Loading vector stores
guidelines_vectorstore = Chroma(persist_directory="./rag_folder/pep_folder", embedding_function=embeddings)
snippets_code_vectorstore = Chroma(persist_directory="./rag_folder/codes_folder", embedding_function=embeddings)

# Defining state graph
# Instanciate an Enum class for answer_state key.
class AnswerState(Enum):
    HALLUCINATED= "hallucinated"
    NOT_COMPLETE= "not complete"
    COMPLETE= "complete"
    NOT_GENERATED= "not generated"
    GENERATED= "generated"

class State(TypedDict):
    code_question: Annotated[str, "The code to be reviewed."]
    retrieved_documents: Annotated[List[Document], "Retrieved documents from vector stores."]
    generated_response: Annotated[str, "Fixed code generated by LLM."]
    iterations: Annotated[int, "Number of iterations for a given user input code."]
    max_iterations: Annotated[int, "Max number of iterations allowed."]
    answer_state: Annotated[AnswerState, "The status of the response."]

async def get_documents(vector_store: Chroma, query: str, result_number: int, search_method: str = "similarity", **kwargs):
    if search_method == "similarity":
        results = vector_store.similarity_search(query = query, k = result_number)
    else:
        results = vector_store.max_marginal_relevance_search(query = query, k = result_number, **kwargs)
    return results

# Define Langgraph nodes and edges
#Nodes

async def retrieve(state: State):
    '''This function takes in input a StateGraph object. 
    It retrieves relevant documents starting from value of state['code_question'] and store them into state['retrieved_documents'] key.'''
    code_question = state['code_question'] # Input code
    answer_state = state['answer_state']
    iterations = state['iterations']
    # Defining how many documents will be retrieved
    pep_docs_number, codes_doc_number = 5, 3
    # Retrying docs search if the generated answer is not complete.
    if answer_state == AnswerState.NOT_COMPLETE:
        lambda_mult = 0.8        
        if iterations >= 2:
            pep_docs_number, codes_doc_number = 8, 4
        if iterations > 2:
            lambda_mult = 0.5
        try:
            async with TaskGroup() as tg:
                guidelines_documents_task = tg.create_task(get_documents(vector_store = guidelines_vectorstore,
                                                                        query = code_question,
                                                                        search_method = "max_marginal",
                                                                        result_number = pep_docs_number,
                                                                        lambda_mult = lambda_mult,
                                                                        ))
                snippets_documents_task = tg.create_task(get_documents(vector_store = snippets_code_vectorstore,
                                                                        query = code_question,
                                                                        search_method = "max_marginal",
                                                                        result_number = codes_doc_number,
                                                                        lambda_mult = lambda_mult,
                                                                        ))
            guidelines_documents = guidelines_documents_task.result()
            snippets_documents = snippets_documents_task.result()
        except* Exception as e: # Handles exceptions for all the tasks
            for error in e.exceptions:
                print(f"Exception occurred: {error}")
        # Merging retrieved documents
        retrieved_documents=[doc for doc in guidelines_documents+snippets_documents]
        return {"retrieved_documents": retrieved_documents}

    # Retrieving docs: first try.
    try:
        async with TaskGroup() as tg:
            guidelines_documents_task = tg.create_task(get_documents(vector_store = guidelines_vectorstore,
                                                                    query = code_question,
                                                                    result_number = pep_docs_number,
                                                            ))
            snippets_documents_task = tg.create_task(get_documents(vector_store = snippets_code_vectorstore,
                                                                    query = code_question,
                                                                    result_number = codes_doc_number,
                                                                ))
        # Retrieving results from tasks
        guidelines_documents = guidelines_documents_task.result()
        snippets_documents = snippets_documents_task.result()
    except* Exception as e: # Handles exceptions for all the tasks
        for error in e.exceptions:
            print(f"Exception occurred: {error}")
    # Merging retrieved documents
    retrieved_documents=[doc for doc in guidelines_documents+snippets_documents]
    return {"retrieved_documents": retrieved_documents}

def evaluate(state: State, documents_evaluator_chain = documents_evaluator_chain):
    '''This function checks whether the documents retrieved are useful or not to fix the code.
    It returns the updated key state["retrieved_documents"] with relevant docs only.'''
    code_question = state['code_question']
    retrieved_documents = state['retrieved_documents']
    relevant_docs= []
    for doc in retrieved_documents:
        try:
            is_relevant = documents_evaluator_chain.invoke({"code": code_question, "document": doc.page_content})
            if is_relevant.score:
                relevant_docs.append(doc)
        except OutputParserException as e:
            print(f"An error occurred while parsing the document score. Check the format of retrieved document:\n{e}")
            continue
        except Exception as e:
            print(f"An unknown exception occurred.\nMore info: {e}")
            break
    return {"retrieved_documents": relevant_docs}

def generate(state: State, rag_pipeline = rag_pipeline, retry_rag_pipeline = retry_rag_pipeline):
    '''This function takes in input the state object.
    It updates the state keys "generated_response" and "iterations" with the generated code and the iteration number respectively.
    '''
    iterations = state['iterations'] + 1
    code_question = state['code_question']
    retrieved_docs = state['retrieved_documents']
    answer_state = state['answer_state']
    # Defining PEP rules and code snippets from retrieved docs for passing them to the prompt.
    # Managing the cases with no rules or no code snippets retrieved.
    rules = "No rules found for this input code. Improve the input code using only code snippets."
    code_snippets = "No significant code snippets found for this input code. Improve the input code using only PEP rules and examples."
    # Separating docs according to their metadatas
    pep_docs = [doc for doc in retrieved_docs if doc.metadata['source'].startswith("pep")]
    snippets_docs = [doc for doc in retrieved_docs if not doc.metadata['source'].startswith("pep")]
    if pep_docs:
        rules = '\n'.join(doc.page_content for doc in pep_docs)
    if snippets_docs:
        code_snippets = '\n'.join(doc.page_content for doc in snippets_docs)
    # Retry generation flow in case of hallucinated answer 
    if answer_state == AnswerState.HALLUCINATED:
        hallucinated_response = state['generated_response']
        response = retry_rag_pipeline.invoke({'code':code_question, 'rules':rules, 'code_snippets':code_snippets, 'hallucinated_response': hallucinated_response})
        match = re.search(r'(?s)</think>\s*(.*)', response)
        response = match.group(1).strip() if match else response.strip()
        return {"generated_response": response, "iterations": iterations}    
    # Main flow
    # Defining prompt for the main flow
    response = rag_pipeline.invoke({'code': code_question, 'rules':rules, 'code_snippets':code_snippets})
    # Clean response from reasoning
    match = re.search(r'(?s)</think>\s*(.*)', response) # This regex allows to extract code from the response since Qwen model always returns a reasoning step.
    response = match.group(1).strip() if match else response.strip()
    answer_state = AnswerState.GENERATED
    return {"generated_response": response, "iterations": iterations, "answer_state": answer_state}

def check_response(state: State, hallucinations_evaluator_chain = hallucinations_evaluator_chain, completeness_evaluator_chain = completeness_evaluator_chain):
    code_question = state['code_question']
    retrieved_documents = state['retrieved_documents']
    response = state["generated_response"]
    context = '\n'.join(doc.page_content for doc in retrieved_documents)
    # Check for hallucinations
    try:
        is_response_hallucinated = hallucinations_evaluator_chain.invoke({"context": context, "response": response})
        if is_response_hallucinated.score:
            return {"answer_state": AnswerState.HALLUCINATED}
        else:
            # Check for completeness
            is_response_complete = completeness_evaluator_chain.invoke({"code": code_question, "response": response})
            if is_response_complete.score:
                return {"answer_state": AnswerState.COMPLETE}
            return {"answer_state": AnswerState.NOT_COMPLETE}
    except OutputParserException as e:
            print(f"An error occurred while parsing the response score: {e}")
            return {"answer_state": AnswerState.COMPLETE}
# Edges
def check_relevance(state: State):
    retrieved_documents = state['retrieved_documents']
    if len(retrieved_documents) > 0:
        return "generate"
    return "END"

def route_answer(state: State):
    iterations= state["iterations"]
    max_iterations = state["max_iterations"]
    answer_state = state["answer_state"]

    if iterations <= max_iterations:
        # Check for hallucinations
        if answer_state == AnswerState.HALLUCINATED:
            return "generate"
        else:
            # Check for completeness
            if answer_state == AnswerState.COMPLETE:
                return "END"
            return "retrieve"
    print("Max tries reached.")
    return "END"